# Generated by Django 5.2.13 on 2026-04-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contactsubmission_galleryimage_newsletterissue_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterIssue',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
