# Generated by Django 5.2.13 on 2026-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_delete_newsletterissue_delete_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ('sort_order', '-updated_at'),
                'abstract': False,
            },
        ),
    ]
