# Generated by Django 5.2.13 on 2026-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('sort_order', '-updated_at'),
                'abstract': False,
            },
        ),
    ]
