# Generated by Django 5.2.13 on 2026-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team_group',
            field=models.CharField(choices=[('academic', 'Academic'), ('eca', 'ECA')], default='academic', max_length=20),
        ),
    ]
