# Generated by Django 5.2.13 on 2026-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_teammember_email_teammember_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('accent_color', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('sort_order', '-updated_at'),
                'abstract': False,
            },
        ),
    ]
