# Generated by Django 5.2.13 on 2026-04-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_jobopening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='jobopening',
            name='location',
        ),
    ]
