# Generated by Django 5.2.13 on 2026-04-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_jobopening_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(blank=True, choices=[('School Life', 'School Life'), ('Academics', 'Academics'), ('Sports', 'Sports'), ('Events', 'Events'), ('Activities', 'Activities')], max_length=100),
        ),
    ]
