# Generated by Django 5.2.13 on 2026-04-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_galleryimage_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='heroslide',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
