# Generated by Django 5.2.13 on 2026-04-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_event_image_remove_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='show_in_overlay',
            field=models.BooleanField(default=False),
        ),
    ]
