# Generated by Django 5.2.13 on 2026-04-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_notice_show_in_overlay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(choices=[('code', 'Code'), ('camera', 'Camera'), ('mic', 'Mic'), ('palette', 'Palette'), ('music', 'Music')], default='code', max_length=50)),
                ('members', models.PositiveIntegerField(default=0)),
                ('meeting_day', models.CharField(blank=True, max_length=100)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('advisor', models.CharField(blank=True, max_length=255)),
                ('color_class', models.CharField(blank=True, max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('sort_order', 'name', '-updated_at'),
                'abstract': False,
            },
        ),
    ]
