# Generated by Django 5.2.13 on 2026-04-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='color_class',
        ),
    ]
